### ISSUE TITLE
How to calculate ADA?

### ISSUE THREAD

**Issue by ianakim** [PouletAxel/SIP_metaploter#4]
Hi, 
This may be a dumb question but where can I find the ADA score? I am trying to calculate ADA score using the code below
`java -jar ${dir}/SIPMeta_1.3.1.jar simple ${loops} ${SIP_output} ${dir}/bullseye.py 21 2000 -c coolwarm -z -res 400 -cpu ${CPU}`
I got a Z-score value plot (attached) but can't find ADA score. The other output files include _APA.tab, _matrix.tab and _strength.tab. 

![ADA_res400_finalLoops_sip06Juicer_bullseye](https://user-images.githubusercontent.com/68685896/166483097-410147e2-47b1-477c-9db5-432fcf86367b.png)

**Comment by jordrow** [comment]
We incorporated ADA into the separate bullseye.py script. It takes the matrix.tab file output by SIPMeta and does the calculation. (Bonus is that it can also be used to quickly replot without having to recalculate the matrix).  Upon running bullseye.py, the ADA score is output to the terminal. 
Usage: python3 bullseye.py --help 
Example: python3 bullseye.py -i yourprefix_matrix.tab -o newFigure -z
Example output to terminal: ADA score is 1.05
Hope this helps! 
-Jordan

**Comment by ianakim** [comment]
Thanks a lot! Have it now.
Iana
